[phases.setup]
nixPkgs = ["elixir", "erlang", "nodejs", "npm"]

[phases.install]
cmds = [
  "mix local.hex --force",
  "mix local.rebar --force",
  "mix deps.get --only prod"
]

[phases.build]
cmds = [
  "mix compile",
  "mix assets.deploy"
]

[start]
cmd = "mix phx.server"